require 'colored'

test_files = FileList['./**/*.test']

o_files = []
test_files.each do |source_file|
	object_file = File.basename(source_file).ext('output')
	o_files << object_file

	file object_file => source_file do |f|
		test_name = File.basename(source_file).ext('')

		print "* Testing '".bold.blue + "#{test_name}".cyan + "'".bold.blue + "..."
		STDOUT.flush

		f = File.new source_file
		data = f.read
		f.close
		array = data.split "---\n"
		source_text = array[0]
		expected_output = array[1]

		o = File.new "#{test_name}.mocha", 'w'
		o.write source_text
		o.close

		output_file = "#{test_name}_out.txt"

		arguments = "#{test_name}.mocha > #{output_file}"
		command = "../samples/command/command #{arguments}"
		`#{command}`

		output_file = File.new output_file
		output_text = output_file.read
		output_file.close

		if expected_output == output_text 
			puts "OK".bold.green
		else
			puts "Failed!".red
		end
		STDOUT.flush
	end
end

file 'tests' => o_files do
	
end

task :default => 'tests'
