/* A recursive-descent parser generated by peg 0.1.9 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 17
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( ctx->begin= ctx->pos, 1)
#endif
#ifndef YY_END
#define YY_END		( ctx->end= ctx->pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *ctx, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *buf;
  int       buflen;
  int       pos;
  int       limit;
  char     *text;
  int       textlen;
  int       begin;
  int       end;
  int       textmax;
  yythunk  *thunks;
  int       thunkslen;
  int       thunkpos;
  YYSTYPE   yy;
  YYSTYPE  *val;
  YYSTYPE  *vals;
  int       valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext yyctx0;
yycontext *yyctx= &yyctx0;
#endif

YY_LOCAL(int) yyrefill(yycontext *ctx)
{
  int yyn;
  while (ctx->buflen - ctx->pos < 512)
    {
      ctx->buflen *= 2;
      ctx->buf= (char *)realloc(ctx->buf, ctx->buflen);
    }
  YY_INPUT((ctx->buf + ctx->pos), yyn, (ctx->buflen - ctx->pos));
  if (!yyn) return 0;
  ctx->limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *ctx)
{
  if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
  ++ctx->pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *ctx, int c)
{
  if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
  if ((unsigned char)ctx->buf[ctx->pos] == c)
    {
      ++ctx->pos;
      yyprintf((stderr, "  ok   yymatchChar(ctx, %c) @ %s\n", c, ctx->buf+ctx->pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(ctx, %c) @ %s\n", c, ctx->buf+ctx->pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *ctx, char *s)
{
  int yysav= ctx->pos;
  while (*s)
    {
      if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
      if (ctx->buf[ctx->pos] != *s)
        {
          ctx->pos= yysav;
          return 0;
        }
      ++s;
      ++ctx->pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *ctx, unsigned char *bits)
{
  int c;
  if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
  c= (unsigned char)ctx->buf[ctx->pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++ctx->pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", ctx->buf+ctx->pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", ctx->buf+ctx->pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *ctx, yyaction action, int begin, int end)
{
  while (ctx->thunkpos >= ctx->thunkslen)
    {
      ctx->thunkslen *= 2;
      ctx->thunks= (yythunk *)realloc(ctx->thunks, sizeof(yythunk) * ctx->thunkslen);
    }
  ctx->thunks[ctx->thunkpos].begin=  begin;
  ctx->thunks[ctx->thunkpos].end=    end;
  ctx->thunks[ctx->thunkpos].action= action;
  ++ctx->thunkpos;
}

YY_LOCAL(int) yyText(yycontext *ctx, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (ctx->textlen < (yyleng + 1))
	{
	  ctx->textlen *= 2;
	  ctx->text= (char *)realloc(ctx->text, ctx->textlen);
	}
      memcpy(ctx->text, ctx->buf + begin, yyleng);
    }
  ctx->text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *ctx)
{
  int pos;
  for (pos= 0;  pos < ctx->thunkpos;  ++pos)
    {
      yythunk *thunk= &ctx->thunks[pos];
      int yyleng= thunk->end ? yyText(ctx, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, ctx->text));
      thunk->action(ctx, ctx->text, yyleng);
    }
  ctx->thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *ctx)
{
  if ((ctx->limit -= ctx->pos))
    {
      memmove(ctx->buf, ctx->buf + ctx->pos, ctx->limit);
    }
  ctx->begin -= ctx->pos;
  ctx->end -= ctx->pos;
  ctx->pos= ctx->thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *ctx, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(ctx);
      yyCommit(ctx);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *ctx, char *text, int count)  { ctx->val += count; }
YY_LOCAL(void) yyPop(yycontext *ctx, char *text, int count)   { ctx->val -= count; }
YY_LOCAL(void) yySet(yycontext *ctx, char *text, int count)   { ctx->val[count]= ctx->yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(ctx, yythunkpos0)

YY_RULE(int) yy_digit(yycontext *ctx); /* 17 */
YY_RULE(int) yy_statement(yycontext *ctx); /* 16 */
YY_RULE(int) yy_parameter(yycontext *ctx); /* 15 */
YY_RULE(int) yy_number(yycontext *ctx); /* 14 */
YY_RULE(int) yy_value(yycontext *ctx); /* 13 */
YY_RULE(int) yy_parameter_list(yycontext *ctx); /* 12 */
YY_RULE(int) yy_function(yycontext *ctx); /* 11 */
YY_RULE(int) yy_function_glyph(yycontext *ctx); /* 10 */
YY_RULE(int) yy_line(yycontext *ctx); /* 9 */
YY_RULE(int) yy_expression(yycontext *ctx); /* 8 */
YY_RULE(int) yy_return(yycontext *ctx); /* 7 */
YY_RULE(int) yy_body(yycontext *ctx); /* 6 */
YY_RULE(int) yy_start(yycontext *ctx); /* 5 */
YY_RULE(int) yy_TERMINATOR(yycontext *ctx); /* 4 */
YY_RULE(int) yy___(yycontext *ctx); /* 3 */
YY_RULE(int) yy_WHITESPACE(yycontext *ctx); /* 2 */
YY_RULE(int) yy__(yycontext *ctx); /* 1 */

YY_ACTION(void) yy_1_number(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_1_number\n"));
   TYRAN_LOG("number!"); ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_line(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_2_line\n"));
   TYRAN_LOG("statement!"); ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_line(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_1_line\n"));
   TYRAN_LOG("line!"); ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_parameter_list(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_1_parameter_list\n"));
   TYRAN_LOG("parameters!"); ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_function(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_1_function\n"));
   TYRAN_LOG("function!"); ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_function_glyph(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_1_function_glyph\n"));
   TYRAN_LOG("function!"); ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_return(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_1_return\n"));
   TYRAN_LOG("return!"); ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_start(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_1_start\n"));
   TYRAN_LOG("start!"); ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_TERMINATOR(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_1_TERMINATOR\n"));
   TYRAN_LOG("TERMINATOR!"); ;
#undef yythunkpos
#undef yypos
#undef yy
}

YY_RULE(int) yy_digit(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "digit"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "digit", ctx->buf+ctx->pos));
  return 1;
  l1:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "digit", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_statement(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "statement"));  if (!yy_return(ctx)) goto l2;
  yyprintf((stderr, "  ok   %s @ %s\n", "statement", ctx->buf+ctx->pos));
  return 1;
  l2:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "statement", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_parameter(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "parameter"));  if (!yy_value(ctx)) goto l3;
  yyprintf((stderr, "  ok   %s @ %s\n", "parameter", ctx->buf+ctx->pos));
  return 1;
  l3:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "parameter", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_number(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "number"));
  l5:;	
  {  int yypos6= ctx->pos, yythunkpos6= ctx->thunkpos;  if (!yy_digit(ctx)) goto l6;  goto l5;
  l6:;	  ctx->pos= yypos6; ctx->thunkpos= yythunkpos6;
  }  yyDo(ctx, yy_1_number, ctx->begin, ctx->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "number", ctx->buf+ctx->pos));
  return 1;
  l4:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "number", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_value(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "value"));  if (!yy_number(ctx)) goto l7;
  yyprintf((stderr, "  ok   %s @ %s\n", "value", ctx->buf+ctx->pos));
  return 1;
  l7:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "value", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_parameter_list(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "parameter_list"));
  l9:;	
  {  int yypos10= ctx->pos, yythunkpos10= ctx->thunkpos;  if (!yy_parameter(ctx)) goto l10;
  l11:;	
  {  int yypos12= ctx->pos, yythunkpos12= ctx->thunkpos;  if (!yymatchChar(ctx, ',')) goto l12;  if (!yy_parameter(ctx)) goto l12;  goto l11;
  l12:;	  ctx->pos= yypos12; ctx->thunkpos= yythunkpos12;
  }  goto l9;
  l10:;	  ctx->pos= yypos10; ctx->thunkpos= yythunkpos10;
  }  yyDo(ctx, yy_1_parameter_list, ctx->begin, ctx->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "parameter_list", ctx->buf+ctx->pos));
  return 1;
  l8:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "parameter_list", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_function(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "function"));  if (!yy__(ctx)) goto l13;  if (!yymatchChar(ctx, '(')) goto l13;  if (!yy__(ctx)) goto l13;  if (!yy_parameter_list(ctx)) goto l13;  if (!yy__(ctx)) goto l13;  if (!yymatchChar(ctx, ')')) goto l13;  if (!yy__(ctx)) goto l13;  if (!yy_function_glyph(ctx)) goto l13;  yyDo(ctx, yy_1_function, ctx->begin, ctx->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "function", ctx->buf+ctx->pos));
  return 1;
  l13:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "function", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_function_glyph(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "function_glyph"));
  {  int yypos15= ctx->pos, yythunkpos15= ctx->thunkpos;  if (!yymatchString(ctx, "->")) goto l16;  goto l15;
  l16:;	  ctx->pos= yypos15; ctx->thunkpos= yythunkpos15;  if (!yymatchString(ctx, "=>")) goto l14;  yyDo(ctx, yy_1_function_glyph, ctx->begin, ctx->end);
  }
  l15:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "function_glyph", ctx->buf+ctx->pos));
  return 1;
  l14:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "function_glyph", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_line(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "line"));
  {  int yypos18= ctx->pos, yythunkpos18= ctx->thunkpos;  if (!yy_expression(ctx)) goto l19;  if (!yy__(ctx)) goto l19;  if (!yy_TERMINATOR(ctx)) goto l19;  yyDo(ctx, yy_1_line, ctx->begin, ctx->end);  goto l18;
  l19:;	  ctx->pos= yypos18; ctx->thunkpos= yythunkpos18;  if (!yy_statement(ctx)) goto l17;  if (!yy__(ctx)) goto l17;  if (!yy_TERMINATOR(ctx)) goto l17;  yyDo(ctx, yy_2_line, ctx->begin, ctx->end);
  }
  l18:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "line", ctx->buf+ctx->pos));
  return 1;
  l17:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "line", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_expression(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "expression"));
  {  int yypos21= ctx->pos, yythunkpos21= ctx->thunkpos;  if (!yy_value(ctx)) goto l22;  goto l21;
  l22:;	  ctx->pos= yypos21; ctx->thunkpos= yythunkpos21;  if (!yy_function(ctx)) goto l20;
  }
  l21:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "expression", ctx->buf+ctx->pos));
  return 1;
  l20:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "expression", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_return(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "return"));  if (!yymatchString(ctx, "return")) goto l23;
  {  int yypos24= ctx->pos, yythunkpos24= ctx->thunkpos;  if (!yy___(ctx)) goto l24;  if (!yy_expression(ctx)) goto l24;  goto l25;
  l24:;	  ctx->pos= yypos24; ctx->thunkpos= yythunkpos24;
  }
  l25:;	  yyDo(ctx, yy_1_return, ctx->begin, ctx->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "return", ctx->buf+ctx->pos));
  return 1;
  l23:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "return", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_body(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "body"));  if (!yy_line(ctx)) goto l26;
  yyprintf((stderr, "  ok   %s @ %s\n", "body", ctx->buf+ctx->pos));
  return 1;
  l26:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "body", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_start(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "start"));  if (!yy_body(ctx)) goto l27;  yyDo(ctx, yy_1_start, ctx->begin, ctx->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "start", ctx->buf+ctx->pos));
  return 1;
  l27:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "start", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_TERMINATOR(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "TERMINATOR"));  if (!yymatchChar(ctx, '\n')) goto l28;  yyDo(ctx, yy_1_TERMINATOR, ctx->begin, ctx->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "TERMINATOR", ctx->buf+ctx->pos));
  return 1;
  l28:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TERMINATOR", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy___(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "__"));  if (!yy_WHITESPACE(ctx)) goto l29;
  l30:;	
  {  int yypos31= ctx->pos, yythunkpos31= ctx->thunkpos;  if (!yy_WHITESPACE(ctx)) goto l31;  goto l30;
  l31:;	  ctx->pos= yypos31; ctx->thunkpos= yythunkpos31;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "__", ctx->buf+ctx->pos));
  return 1;
  l29:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "__", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_WHITESPACE(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "WHITESPACE"));
  {  int yypos33= ctx->pos, yythunkpos33= ctx->thunkpos;  if (!yymatchChar(ctx, '\t')) goto l34;  goto l33;
  l34:;	  ctx->pos= yypos33; ctx->thunkpos= yythunkpos33;  if (!yymatchChar(ctx, ' ')) goto l32;
  }
  l33:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "WHITESPACE", ctx->buf+ctx->pos));
  return 1;
  l32:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "WHITESPACE", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy__(yycontext *ctx)
{
  yyprintf((stderr, "%s\n", "_"));
  l36:;	
  {  int yypos37= ctx->pos, yythunkpos37= ctx->thunkpos;  if (!yy_WHITESPACE(ctx)) goto l37;  goto l36;
  l37:;	  ctx->pos= yypos37; ctx->thunkpos= yythunkpos37;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", ctx->buf+ctx->pos));
  return 1;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *ctx);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->buflen)
    {
      yyctx->buflen= 1024;
      yyctx->buf= (char *)malloc(yyctx->buflen);
      yyctx->textlen= 1024;
      yyctx->text= (char *)malloc(yyctx->textlen);
      yyctx->thunkslen= 32;
      yyctx->thunks= (yythunk *)malloc(sizeof(yythunk) * yyctx->thunkslen);
      yyctx->valslen= 32;
      yyctx->vals= (YYSTYPE *)malloc(sizeof(YYSTYPE) * yyctx->valslen);
      yyctx->begin= yyctx->end= yyctx->pos= yyctx->limit= yyctx->thunkpos= 0;
    }
  yyctx->begin= yyctx->end= yyctx->pos;
  yyctx->thunkpos= 0;
  yyctx->val= yyctx->vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_start);
}

#endif
