typedef enum
{
	/* Stack */
	TN_OP_NOP,
	TN_OP_PUSH_NUMBER,
	TN_OP_PUSH_STRING,
	TN_OP_PUSH_VARIABLE,
	TN_OP_PUSH_UNDEFINED,
	TN_OP_PUSH_BOOLEAN,
	TN_OP_PUSH_FUNCTION,
	TN_OP_PUSH_SCOPE,
	TN_OP_PUSH_THIS,
	TN_OP_PUSH_TOP,
	TN_OP_PUSH_TOP2,
	TN_OP_POP,

	/* Arithmetic */
	TN_OP_NEGATIVE, 
	TN_OP_POSITIVE,
	TN_OP_NOT,
	TN_OP_ADD,
	TN_OP_SUBTRACT,
	TN_OP_MULTIPLY,
	TN_OP_DIVIDE,
	TN_OP_MODULUS,
	TN_OP_INCREASE,
	TN_OP_DECREASE,

	/* Bitwise */
	TN_OP_BITWISE_AND,
	TN_OP_BITWISE_OR,
	TN_OP_BITWISE_XOR,
	TN_OP_BITWISE_NOT,
	TN_OP_BITWISE_SHIFT,

	/* Compares */
	TN_OP_COMPARE_EQUAL,
	TN_OP_COMPARE_NOT_EQUAL,
	TN_OP_COMPARE_LESS,
	TN_OP_COMPARE_GREATER,
	TN_OP_COMPARE_LESS_EQUAL,
	TN_OP_COMPARE_GREATER_EQUAL,
	TN_OP_COMPARE_STRICT_EQUAL,
	TN_OP_COMPARE_STRICT_NOT_EQUAL,

	/* Jump and call */
	TN_OP_JUMP,
	TN_OP_JUMP_POP,
	TN_OP_JUMP_TRUE,
	TN_OP_JUMP_FALSE,
	TN_OP_JUMP_TRUE_POP,
	TN_OP_JUMP_FALSE_POP,

	TN_OP_CALL,	
	TN_OP_NEW,		
	TN_OP_RETURN,

	/* Object manipulation */
	TN_OP_MAKE_OBJECT,
	TN_OP_MAKE_ARRAY,
	TN_OP_DELETE,
	TN_OP_ASSIGN,
	TN_OP_SUBSCRIPT,
	TN_OP_UNREFERENCE,

	/* Object iteration */
	TN_OP_KEY,
	TN_OP_NEXT,

	/* Other */
	TN_OP_LOAD_THIS,
	TN_OP_INTERNAL,
	
	TN_OP_MAX_ID
} tyran_opcode_id;
